name: Docker Build
on:
  - push
jobs:
  Docker-Builder:
    runs-on:
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: false
          build-args:
            - MINECRAFT_VERSION=1.17.1
